# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SvamitvaPPM
                                 A QGIS plugin
 Svamitva
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-15
        copyright            : (C) 2025 by Surveyor Stories
        email                : surveyorstories@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Surveyor Stories'
__date__ = '2025-07-15'
__copyright__ = '(C) 2025 by Surveyor Stories'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SvamitvaPPM class from file SvamitvaPPM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Gruhanaksha import SvamitvaPPMPlugin
    return SvamitvaPPMPlugin(iface)
