# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SvamitvaPPM
                                 A QGIS plugin
 Svamitva
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-15
        copyright            : (C) 2025 by Surveyor Stories
        email                : surveyorstories@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Surveyor Stories'
__date__ = '2025-07-15'
__copyright__ = '(C) 2025 by Surveyor Stories'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from qgis.core import QgsProject

import os.path
from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    qVersion,
    QCoreApplication
)


import os
import sys
import inspect
from qgis.utils import iface
from qgis.PyQt.QtWidgets import QAction, QMenu
from qgis.PyQt.QtGui import QIcon
import processing

from qgis.core import QgsProcessingAlgorithm, QgsApplication, Qgis
from .Gruhanaksha_provider import SvamitvaPPMProvider
from PyQt5.QtCore import Qt
from .master import MasterWidget
from .tools import ToolWidget

# from .topo_layout_box import ToolSet, UpdateFieldValues
cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

master = MasterWidget()
tools = ToolWidget()

qgis_main_window = iface.mainWindow()
tools.setParent(qgis_main_window, Qt.Window)


class SvamitvaPPMPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        self.canvas = iface.mapCanvas()

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SvamitvaPPMProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

        # Create the toolbar
        self.toolbar = self.iface.addToolBar('Gruhanaksha')
        self.toolbar.setObjectName('Gruhanaksha Toolbar')

        # Define action with icon and label
        # Make sure this file exists
        icon_path = os.path.join(os.path.join(cmd_folder, 'images/ppm.svg'))
        icon = QIcon(icon_path)
        self.action = QAction(icon, "PPM Generation", self.iface.mainWindow())
        self.dropdown_button = QAction(
            QIcon(icon), "Maps", self.iface.mainWindow())
        self.action.triggered.connect(self.run_svamitva_algorithm)
        self.dropdown_button.triggered.connect(self.run_svamitva_algorithm)

        # self.toolbar.addAction(self.action)
        self.iface.addPluginToMenu("&Gruhanaksha", self.action)
        # master panel
        self.action_master = QAction(QIcon(icon_path), 'Master Data',
                                     self.iface.mainWindow())
        self.action_master.triggered.connect(self.master_data)
        self.iface.addPluginToMenu(
            u"&Gruhanaksha", self.action_master)

        # Define tools with icon and label
        # Make sure this file exists
        icon_path = os.path.join(os.path.join(cmd_folder, 'images/ppm.svg'))
        topo = os.path.join(os.path.join(cmd_folder, 'images/topo.svg'))

        self.action_tools = QAction(
            QIcon(topo), "Tools", self.iface.mainWindow())

        self.dropdown_button = QAction(
            QIcon(icon), "PPMs", self.iface.mainWindow())
        self.action_tools.triggered.connect(self.show_tools)
        self.dropdown_button.triggered.connect(self.run_svamitva_algorithm)

        # Create a dropdown menu

        self.dropdown_menu = QMenu("Maps Menu")
        # Add actions to the dropdown menu
        self.dropdown_menu.addAction(self.action_master)
        self.dropdown_menu.addAction(self.action)

        # Create a button in the toolbar to display the dropdown menu with an icon
        self.dropdown_button.setMenu(self.dropdown_menu)
        self.toolbar.addAction(self.dropdown_button)
        self.toolbar.addAction(self.action_tools)

    # def unload(self):
    #     QgsApplication.processingRegistry().removeProvider(self.provider)

    def unload(self):
        """Remove plugin from GUI and unregister provider"""
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)
        if self.action:
            self.iface.removePluginMenu("&Gruhanaksha", self.action)
            if self.toolbar:
                self.toolbar.removeAction(self.action)
        if self.toolbar:
            del self.toolbar
        self.iface.removePluginMenu(
            u"Gruhanaksha", self.action_master)
        self.iface.unregisterMainWindowAction(self.action_master)

        self.iface.removePluginMenu(
            u"Gruhanaksha", self.action_tools)
        self.iface.unregisterMainWindowAction(self.action_tools)

    def run_svamitva_algorithm(self):
        """Trigger custom logic or Processing algorithm"""
        processing.execAlgorithmDialog("Gruhanaksha:ppm_new_model")

    def master_data(self):
        if QgsProject.instance().fileName():
            master.show()
        else:
            asksaveProject()

    def show_tools(self):
        if QgsProject.instance().fileName():
            # Always create a new ToolWidget instance to avoid using a deleted object

            tools.show()
        else:
            asksaveProject()


def asksaveProject():
    """
    Version that uses QGIS built-in save functionality.

    Returns:
        bool: True if project was saved successfully, False otherwise.
    """
    project = QgsProject.instance()

    if project.fileName():
        # Project has filename, save directly
        return project.save()
    else:
        # Use QGIS built-in save as functionality
        from qgis.utils import iface
        iface.actionSaveProjectAs().trigger()  # This opens the Save As dialog

        # Check if project now has a filename (user saved it)
        if project.fileName():
            iface.messageBar().pushMessage("Success", "Project saved successfully.",
                                           level=Qgis.Success, duration=3)
            return True
        else:
            iface.messageBar().pushMessage("Warning", "Project was not saved.",
                                           level=Qgis.Warning, duration=3)
            return False
