name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Extract version from commit message
        id: extract_version
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          if [ -z "$version" ]; then
            echo "No version found in commit message"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV

      - name: Read release notes
        run: |
          if [ ! -f release.md ]; then
            echo "No release notes found"
            exit 1
          fi
          echo "RELEASE_NOTE<<EOF" >> $GITHUB_ENV
          cat release.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Compress repository
        run: |
          cd ..
          zip -r gruhanaksha/gruhanaksha_${{ env.version }}.zip gruhanaksha \
            -x "gruhanaksha/.git*" "gruhanaksha/.github/*" "gruhanaksha/*.html" "gruhanaksha/release.zip" "gruhanaksha/gruha.zip"
          cd gruhanaksha

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.version }}
          name: "Gruhanaksha ${{ env.version }}"
          body: ${{ env.RELEASE_NOTE }}
          artifacts: gruhanaksha_${{ env.version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
